version: "3"
services:
  db:
    image: mariadb:10.3
    restart: always
    environment:
      - MYSQL_DATABASE=radius
      - MYSQL_USER=radius
      - MYSQL_PASSWORD=radpass
      - MYSQL_ROOT_PASSWORD=radpass
    volumes:
      - dbdata:/var/lib/mysql
      - ./initdb.d/radius.sql:/docker-entrypoint-initdb.d/radius.sql
  radius:
    build:
      context: radius
    restart: always
    depends_on:
      - db
    ports:
      - 1812:1812/tcp
      - 1812:1812/udp
      - 1813:1813/tcp
      - 1813:1813/udp
      - 11812:11812/tcp
      - 11812:11812/udp
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=radius
      - DB_USER=radius
      - DB_PASSWORD=radpass
      - RAD_DEBUG=yes
      - RADIUS_KEY=testing123
      - RAD_CLIENTS=*
  captiveportal:
    build:
      dockerfile: php7-apache2-pdo-dockerfile
      context: .
    restart: always
    ports:
      - 8080:80
    environment:
      - NBI_USERNAME=api
      - NBI_PASSWORD=ruckus@123
      - DB_TYPE=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=radius
      - DB_USER=radius
      - DB_PASSWORD=radpass
    volumes:
      - ./captive-portal:/var/www/html
  manager:
    build:
      dockerfile: php7-apache2-pdo-dockerfile
      context: .
    restart: always
    depends_on:
      - db
    ports:
      - 8081:80
    environment:
      - DB_TYPE=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=radius
      - DB_USER=radius
      - DB_PASSWORD=radpass
    volumes:
      - ./manager:/var/www/html
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    environment:
      - ADMINER_DEFAULT_SERVER=db
    ports:
      - 8082:8080

networks:
  default:
    ipam:
      config:
        - subnet: 10.0.0.0/24

volumes:
  dbdata:
